sonar.projectKey=hireconnect-frontend
sonar.projectName=HireConnect Frontend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9001

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/*.spec.ts,**/*.scss
sonar.coverage.exclusions=**/*.spec.ts,**/*.module.ts,src/main.ts,src/polyfills.ts,src/environments/**,src/app/features/**/*.component.ts
sonar.cpd.exclusions=src/app/core/models/**,src/**/*.html,src/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/hireconnect-frontend/lcov.info
sonar.typescript.tsconfigPath=tsconfig.sonar.json
